name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:                                         # Defines the different configurations to test against:
        version:                                      #   - Julia versions to test.
          - '1.8'
          - 'nightly'
        os:                                           #   - Operating systems to test.
          - ubuntu-latest
        arch:                                         #   - Architectures to test.
          - x64
    steps:
      - uses: actions/checkout@v6                     # Fetches the code from the Git repository.
      - uses: julia-actions/setup-julia@v2            # Installs the specific version from the matrix 
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1                  # Speeds up the build process by reusing previously downloaded and compiled dependencies
      - uses: julia-actions/julia-buildpkg@v1         # Builds the package
      - uses: julia-actions/julia-runtest@v1          # Executes the code in test/runtests.jl. This is the core check.
      - uses: julia-actions/julia-processcoverage@v1  # Generates code coverage data
      - uses: codecov/codecov-action@v5               # Uploads the code coverage report (lcov.info) to an external service like 
        with:
          files: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6                     # Fetches the code from the Git repository.              
      - uses: julia-actions/setup-julia@v2            # Installs the latest stable Julia version    
        with:
          version: '1'                                # Use the latest stable Julia 1.x version
      - uses: julia-actions/julia-buildpkg@v1         # Builds the package
      - uses: julia-actions/julia-docdeploy@v1        # Builds builds the documentation using Documenter.jl and then automatically deploys the generated HTML files to a designated branch of the repository (often gh-pages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using WaveSpec
            DocMeta.setdocmeta!(WaveSpec, :DocTestSetup, :(using WaveSpec); recursive=true)
            doctest(WaveSpec)'
